-- Admin-editable Policies & Cancellations page. Same site_content key/value
-- pattern as every other CMS block; body is markdown, rendered on the
-- storefront with react-markdown. Pre-filled with a reasonable draft the
-- owner can edit in the admin (Homepage Editor -> Policies tab).
insert into public.site_content (key, value) values
  ('policies', '{
    "title_en": "Policies & Cancellations",
    "title_ar": "السياسات والإلغاء",
    "body_md_en": "## Order Cancellations\n\nYou can cancel your order free of charge as long as it has not yet been shipped. To cancel, contact us via WhatsApp or email with your order number as soon as possible.\n\nOnce an order has been handed to the courier, it can no longer be cancelled and falls under our Returns policy instead.\n\n## Returns & Exchanges\n\n- Items can be returned or exchanged within **14 days** of delivery.\n- Items must be unworn, in their original condition, and in the original box/packaging.\n- Sale items are final sale and cannot be returned unless defective.\n- To start a return or exchange, contact us with your order number and the reason for the return.\n\n## Refunds\n\n- Approved refunds are issued to the original payment method (Kashier) within **5-7 business days** of us receiving the returned item.\n- Cash on Delivery orders are refunded via bank transfer or store credit, your choice.\n- Shipping fees are non-refundable unless the return is due to our error (wrong item, defect, damage).\n\n## Damaged or Incorrect Items\n\nIf your order arrives damaged or you received the wrong item, contact us within **48 hours** of delivery with photos of the item and packaging. We will arrange a free replacement or full refund, including shipping.\n\n## Shipping & Delivery\n\n- Delivery times vary by governorate and are shown at checkout.\n- Cash on Delivery is available; the courier will call before delivery.\n- Once your order ships, you will receive updates on its status.\n\n## Contact Us\n\nFor any questions about an order, cancellation, or return, reach us through the WhatsApp button on the site or the contact details in the footer.",
    "body_md_ar": "## إلغاء الطلب\n\nيمكنك إلغاء طلبك مجانًا طالما لم يتم شحنه بعد. للإلغاء، تواصل معنا عبر واتساب أو البريد الإلكتروني برقم الطلب في أقرب وقت ممكن.\n\nبعد تسليم الطلب لشركة الشحن، لا يمكن إلغاؤه ويخضع عندها لسياسة الإرجاع.\n\n## الإرجاع والاستبدال\n\n- يمكن إرجاع أو استبدال المنتجات خلال **14 يومًا** من تاريخ الاستلام.\n- يجب أن تكون المنتجات غير مستخدمة وبحالتها الأصلية وبعلبتها الأصلية.\n- منتجات التخفيضات نهائية ولا يمكن إرجاعها إلا في حالة وجود عيب.\n- لبدء عملية إرجاع أو استبدال، تواصل معنا برقم الطلب وسبب الإرجاع.\n\n## استرداد الأموال\n\n- يتم استرداد المبالغ المعتمدة لنفس وسيلة الدفع الأصلية (كاشير) خلال **5-7 أيام عمل** من استلامنا للمنتج المرتجع.\n- طلبات الدفع عند الاستلام تُسترد عن طريق تحويل بنكي أو رصيد في المتجر، حسب اختيارك.\n- رسوم الشحن غير قابلة للاسترداد إلا إذا كان الإرجاع بسبب خطأ منا (منتج خاطئ، عيب، تلف).\n\n## المنتجات التالفة أو الخاطئة\n\nإذا وصل طلبك تالفًا أو استلمت منتجًا خاطئًا، تواصل معنا خلال **48 ساعة** من الاستلام مع صور للمنتج والتغليف. سنقوم بترتيب استبدال مجاني أو استرداد كامل شامل الشحن.\n\n## الشحن والتوصيل\n\n- تختلف مدة التوصيل حسب المحافظة وتظهر عند الدفع.\n- خدمة الدفع عند الاستلام متاحة، وسيتصل بك مندوب التوصيل قبل الوصول.\n- بمجرد شحن طلبك، ستصلك تحديثات عن حالته.\n\n## تواصل معنا\n\nلأي استفسار عن طلب أو إلغاء أو إرجاع، تواصل معنا عبر زر واتساب في الموقع أو بيانات التواصل في أسفل الصفحة."
  }'::jsonb)
on conflict (key) do nothing;
